services:
  ui_sonarqube:
    image: sonarqube:lts-community
    depends_on:
      - sonar_db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9001:9000"
    volumes:
      - ui_sonarqube_conf:/opt/sonarqube/conf
      - ui_sonarqube_data:/opt/sonarqube/data
      - ui_sonarqube_extensions:/opt/sonarqube/extensions
      - ui_sonarqube_logs:/opt/sonarqube/logs
      - ui_sonarqube_temp:/opt/sonarqube/temp

ui_sonar_db:
    image: postgres:13
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - ui_sonar_db:/var/lib/postgresql
      - ui_sonar_db_data:/var/lib/postgresql/data

volumes:
  ui_sonarqube_conf:
  ui_sonarqube_data:
  ui_sonarqube_extensions:
  ui_sonarqube_logs:
  ui_sonarqube_temp:
  ui_sonar_db:
  ui_sonar_db_data: